### ISSUE TITLE
Initial Issues

### ISSUE THREAD

**Issue by seencasey** [alexlo94/acaciajudge.com-#8]
1. Rainbow color on categories is supposed to be on hover, not all the time.
2. When a category is selected on the left, text should be bold & black.
3. Add twitter and email icons to the social icons
4. For mobile site: CENTER page titles and CENTER social icons and footer in the menu.
5. Link custom domain.

**Comment by alexlo94** [comment]
# Fixes
1. Done. every link is bolded on hover and the work category links have their specific color.
2. Done. The appropriate category is bolded black when the user is on one of the pages accessible through the links on the sidebar. Note that project pages are not associated with **one** specific category so they do not bold any links.
3. Done. They also now link to your social media.
4. Done. I've implemented a rule that centers all h1, h2, and h3 tags under a certain container width. I can extend this to h4, h5, and h6 but they're used as captions/small text (they're smaller than paragraph text) so that would affect how your portfolio grid looks like. Let me know if you want me to do this.

# Bonus
1. Added home link to the logo.
